#my_string=input('Место последней работы ')
#print(len("Место последней работы"))
my_string=("North-Caucasus Federal University")
print (my_string.upper())
print (my_string.lower())
print(my_string.replace ( " ",""))
print(my_string[0])
print(my_string[-1])
print(my_string[::-1])
print(my_string[::2])